env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: {
  import/extensions: 'off',
#  import/prefer-default-export: 'off',
#  no-lonely-if: 'off'
}
